### ISSUE TITLE
Users of vintage gallery plugin "myGallery" are updated to this unrelated gallery plugin

### ISSUE THREAD

**Issue by iamwebrocker** [zalevsk1y/my-slider-gallery#2]
Hi,

this is less of an issue but more of a heads-up to users of the plugin "myGallery" by Thomas Boley that once existed -- it seems that by having used the same name in this plugin here, but then renaming it to "MySliderGallery" and _then_ publishing it to the WP Plugin Directory, those old installs of that totally unrelated plugin are now being updated to this new plugin - which is a bit unexpected.

![update-1](https://user-images.githubusercontent.com/1223080/66759325-57feb880-eea0-11e9-9be5-660f46e57528.png)
![update-2](https://user-images.githubusercontent.com/1223080/66759326-57feb880-eea0-11e9-843a-b6fde2310ece.png)

**Comment by zalevsk1y** [comment]
Hi, I talked with the author of the plugin about this . Here is a [link](https://wordpress.org/support/topic/copyright-11/) to our correspondence. I'm sorry that it happened, but the original plugin was closed and according to the rules of the community [“Take Over an Existing Plugin”](https://developer.wordpress.org/plugins/wordpress-org/take-over-an-existing-plugin/):

> “If a plugin is closed because it was unused, you can skip the rest of this and email plugins@wordpress.org right away.”

**Comment by iamwebrocker** [comment]
> Here is a link to our correspondence

ah, ok, thanks. didn't notice that this already has been addressed.

**Comment by zalevsk1y** [comment]
There are two ways to solve this problem:
- just do not update the plugin. And do not pay attention to the update notification.
-change plugin name in main plugin file. Example:
`Plugin Name: VintageMyGallery`.
